### ISSUE TITLE
Watchedlist doesn't update 

### ISSUE THREAD

**Issue by marquavious** [soggybag/MyMovies#1]
The watched list doesn't update and sometimes not at all when adding from the detailed view.

**Comment by soggybag** [comment]
I made two changes to WatchedViewController. Look for the "***". The watch list was loaded in viewDidLoad but this not called when this view subsequently appears. In other words it only happens the first time the view appears. 

viewWillAppear on the other hand is called each time the view will appear. We need to possibly update the watched list each we return because you may have added a new movie to the watch list.
